{{- if .Values.clusters }}
{{- $operatorName := include "operator.fullname"  . }}
{{- $operatorLabels := include "operator.labels" . }}
{{- range $cname, $cvalues := .Values.clusters }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $operatorName }}-{{ $cname }}-cluster
  labels:
    {{- $operatorLabels | nindent 4 }}
data:
  {{- range $k, $v := $cvalues }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
