{{- if .Values.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operator.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.config | toYaml | b64enc }}
{{- end }}
