{{- if .Values.webhooks.listen }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operator.fullname" . }}-webhooks-tls
  labels:
    {{- include "operator.labels" . | nindent 4 }}
type: Opaque
{{- end }}
