{{- if .Values.webhooks.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}-webhooks
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhooks.service.type }}
  ports:
    - port: {{ .Values.webhooks.service.port }}
      targetPort: webhooks-https
      protocol: TCP
      name: https
  selector:
    {{- include "operator.selectorLabels" . | nindent 4 }}
{{- end -}}
