{{- if .Values.metrics.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}-metrics
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: metrics-http
      protocol: TCP
      name: http
  selector:
    {{- include "operator.selectorLabels" . | nindent 4 }}
{{- end -}}
