COMPONENT_NAME: platform-service-project-workspace
COMPONENT_NAME_PREFIX: github.com/openmcp-project
PROVIDER: openmcp-project
COMPONENT_REPO_PREFIX: ghcr.io/openmcp-project/platform-service-project-workspace