# permissions for end users to view workspaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workspace-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: project-workspace-operator
    app.kubernetes.io/part-of: project-workspace-operator
    app.kubernetes.io/managed-by: kustomize
  name: workspace-viewer-role
rules:
- apiGroups:
  - core.openmcp.cloud
  resources:
  - workspaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.openmcp.cloud
  resources:
  - workspaces/status
  verbs:
  - get
