# Default values for project-workspace-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicaCount: 1
  minReadySeconds: 5
  maxSurge: 1
  maxUnavailable: 0

  topologySpreadConstraints:
    enabled: false
    maxSkew: 1

  leaderElection:
    enabled: false
    leaseNamespace: default

image:
  repository: ghcr.io/openmcp-project/images/project-workspace-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v0.13.0@sha256:ea7129d353c8dc68fa46c05264f6c1841daeaba88a4045246543ea832dd142c6

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
 # project:
 #   resourcesBlockingDeletion:
 #     - group: ""
 #       version: "v1"
 #       kind: "Secret"
 # workspace:
 #   resourcesBlockingDeletion:
 #     - group: ""
 #       version: "v1"
 #       kind: "Secret"

clusters:
  # crate:
  #   # specify either kubeconfig or host, audience, and one of caData or caConfigMapName.
  #   kubeconfig: |
  #     apiVersion: v1
  #     clusters:
  #     - cluster: ...
  #   host: https://api.mycluster.com
  #   audience: ...
  #   caData: ...
  #   caConfigMapName: ...

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

init:
  enabled: true

  args: []
  extraArgs: []

  env: []
  # Extra environment variables to add to the init container.
  extraEnv: []

  # Volumes to mount to the init container.
  volumeMounts: []
  # Extra volumes to mount to the init container.
  extraVolumeMounts: []

manager:
  args: []
  extraArgs: []

  env: []
  # Extra environment variables to add to the manager container.
  extraEnv: []

  # Volumes to mount to the manager container.
  volumeMounts: []
  # Extra volumes to mount to the manager container.
  extraVolumeMounts: []

# Volumes to pass to pod.
volumes: []

# Extra volumes to pass to pod.
extraVolumes: []

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsNonRoot: true
  runAsUser: 65532 # nonroot user id for gcr.io/distroless/static:nonroot
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

crds:
  manage: true

metrics:
  listen:
    port: 8080
  service:
    enabled: false
    port: 8080
    type: ClusterIP
    annotations: {}

webhooks:
  manage: true
  url: ""
  listen:
    port: 9443
  service:
    enabled: true
    port: 443
    type: ClusterIP
    annotations: {}
  # memberOverrides:
  #   memberOverridesName: override-1
  
rbac:
  clusterRole:
    rules: []
  role:
    rules: []

nodeSelector: {}

tolerations: []

affinity: {}
